### ISSUE TITLE
Unhandled Exception on a Master Detail project when hitting back button

### ISSUE THREAD

**Issue by jmjcoelho** [PrismLibrary/Prism-Samples-Forms#8]
Good afternoon Brian

  I'm using Prism for a Xamarin Forms project, I have followed your master detail example but when I hit the back button I've got this error "Java.Lang.IllegalStateException: Activity has been destroyed", I downloaded your example to see i I was doing something wrong on my project but the same thing happens. 
  Do you have any idea why or how to stop fix the issue?

Many thanks for all your work
Jose coelho

**Comment by brianlagunas** [comment]
Turns out this is related to Xamarin.Forms 2.3.3, supposedly fixed in 2.3.4-pre1 related to fragment handling with masterdetailpages.

**Comment by jmjcoelho** [comment]
I installed Xamarin.Forms 2.3.4-pre1 and the problem is still there, what is interesting is that this doesn't happens on a project without Prism, that is why I thought the problem was on Prism itself rather than on Xamarin.Forms!

  Do you know any work around?


 Many thanks for you response
Jose Coelho

**Comment by brianlagunas** [comment]
Prism does nothing related to any activities or their destruction.  Prism only abstracts away the navigation complexities into VM's.  I do not know of a work around as this has only been reported once and it was fixed by upgrading to the latest preview of XF.

**Comment by jmjcoelho** [comment]
This was definitely not fix because I'm still getting the same error on the latest preview of XF, unless that this is different issue! 
  This only happens when there are no more pages on the navigation stack and the app goes to the background.

Any way thanks for your help, I really appreciate your work and think that Prism is a great library
